#1.Load The Dataset

In [ ]:
import pandas as pd
train_pd = pd.read_csv("train.csv")
train_pd

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
train_pd = train_pd[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
train_pd

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
train_pd = train_pd.dropna()
train_pd

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
885         0       3  female  39.0      0      5  29.1250        Q
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[712 rows x 8 columns]

In [ ]:
train_pd.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  712.000000  712.000000  712.000000  712.000000  712.000000  712.000000
mean     0.404494    2.240169   29.642093    0.514045    0.432584   34.567251
std      0.491139    0.836854   14.492933    0.930692    0.854181   52.938648
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.000000    0.000000    0.000000    8.050000
50%      0.000000    2.000000   28.000000    0.000000    0.000000   15.645850
75%      1.000000    3.000000   38.000000    1.000000    1.000000   33.000000
max      1.000000    3.000000   80.000000    5.000000    6.000000  512.329200

#2.Encoding & Preprocessing Data

In [ ]:
# to_categorical : Cette fonction convertit des étiquettes entières (ex: [0, 1, 2]) en vecteurs binaires "one-hot encoded" (ex: [[1,0,0], [0,1,0], [0,0,1]]).
# pclass-1 : to_categorical attend des étiquettes commencant à 0 (ex: 0 pour la 1ère classe, 1 pour la 2ème, etc.).
#            Ici, Pclass va de 1 à 3, donc on décale pour obtenir [0, 1, 2].

from tensorflow.keras.utils import to_categorical

pclass = train_pd['Pclass'].to_numpy()
as_categorical_pclass = to_categorical(pclass-1, num_classes = 3)
as_categorical_pclass

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [ ]:
train_pd['Sex'] = train_pd['Sex'].replace({'male' : 1, 'female': 0})
as_binary_sex = train_pd['Sex'].to_numpy()
as_binary_sex


/tmp/ipython-input-895278693.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_pd['Sex'] = train_pd['Sex'].replace({'male' : 1, 'female': 0})
/tmp/ipython-input-895278693.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_pd['Sex'] = train_pd['Sex'].replace({'male' : 1, 'female': 0})


array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,

In [ ]:
age_np = train_pd['Age'].to_numpy()
age_np = (age_np -age_np.mean()) / age_np.std()
age_np

array([-0.52766856,  0.57709388, -0.25147795,  0.36995092,  0.36995092,
        1.68185631, -1.9086216 , -0.1824303 , -1.08004977, -1.77052629,
        1.95804692, -0.66576386,  0.64614153, -1.08004977,  1.75090396,
       -1.9086216 ,  0.09376031,  0.36995092,  0.30090327, -1.01100212,
       -0.11338265, -1.49433569,  0.57709388, -0.73481151,  0.71518918,
        2.51042813, -0.11338265,  0.85328448, -0.59671621, -0.80385917,
       -1.08004977,  0.71518918, -0.1824303 , -1.83957395, -0.73481151,
       -0.80385917, -1.56338334, -0.59671621,  1.33661805, -0.04433499,
        2.44138048, -0.59671621, -0.07885882, -1.70147864, -1.28719273,
       -0.52766856,  1.06042744, -1.77052629, -0.04433499, -0.73481151,
       -0.87290682, -0.25147795,  0.16280796, -0.94195447, -0.59671621,
       -0.25147795,  0.16280796, -0.3205256 , -1.98940735,  0.02471266,
       -0.52766856, -0.04433499, -0.11338265, -0.87290682,  0.23185562,
       -0.94195447, -0.45862091, -0.38957325, -0.04433499, -0.66

In [ ]:
sibsp_np = train_pd['SibSp'].to_numpy()

#Scaling
sibsp_np= (sibsp_np -sibsp_np.mean()) / sibsp_np.std()
sibsp_np

array([ 0.52251079,  0.52251079, -0.55271372,  0.52251079, -0.55271372,
       -0.55271372,  2.67295981, -0.55271372,  0.52251079,  0.52251079,
       -0.55271372, -0.55271372,  0.52251079, -0.55271372, -0.55271372,
        3.74818432,  0.52251079, -0.55271372, -0.55271372, -0.55271372,
       -0.55271372,  2.67295981,  0.52251079,  2.67295981, -0.55271372,
       -0.55271372,  0.52251079,  0.52251079, -0.55271372,  1.5977353 ,
        0.52251079,  0.52251079,  0.52251079,  0.52251079, -0.55271372,
        0.52251079,  3.74818432, -0.55271372,  0.52251079,  0.52251079,
       -0.55271372, -0.55271372, -0.55271372,  0.52251079,  4.82340884,
       -0.55271372,  0.52251079,  2.67295981, -0.55271372, -0.55271372,
        3.74818432,  1.5977353 , -0.55271372,  4.82340884, -0.55271372,
        0.52251079, -0.55271372, -0.55271372, -0.55271372, -0.55271372,
       -0.55271372, -0.55271372, -0.55271372, -0.55271372,  2.67295981,
        0.52251079,  2.67295981, -0.55271372, -0.55271372, -0.55

In [ ]:
parch_np= train_pd['Parch'].to_numpy()

#Scaling
parch_np= (parch_np -parch_np.mean()) / parch_np.std()
parch_np

array([-0.50678737, -0.50678737, -0.50678737, -0.50678737, -0.50678737,
       -0.50678737,  0.66474707,  1.83628152, -0.50678737,  0.66474707,
       -0.50678737, -0.50678737,  5.35088486, -0.50678737, -0.50678737,
        0.66474707, -0.50678737, -0.50678737, -0.50678737, -0.50678737,
       -0.50678737,  0.66474707,  5.35088486,  1.83628152, -0.50678737,
       -0.50678737, -0.50678737, -0.50678737, -0.50678737, -0.50678737,
       -0.50678737, -0.50678737, -0.50678737,  1.83628152, -0.50678737,
       -0.50678737,  0.66474707, -0.50678737, -0.50678737, -0.50678737,
        0.66474707, -0.50678737, -0.50678737,  1.83628152,  1.83628152,
       -0.50678737, -0.50678737,  1.83628152, -0.50678737, -0.50678737,
        1.83628152, -0.50678737, -0.50678737,  1.83628152, -0.50678737,
       -0.50678737, -0.50678737, -0.50678737,  1.83628152, -0.50678737,
       -0.50678737, -0.50678737, -0.50678737, -0.50678737, -0.50678737,
        3.00781597,  1.83628152, -0.50678737, -0.50678737, -0.50

In [ ]:
fare = train_pd['Fare']
fare_np = fare.to_numpy()

#Scaling
fare_np = (fare_np -fare_np.mean()) / fare_np.std()
fare_np

array([-5.16379924e-01,  6.94046048e-01, -5.03620351e-01,  3.50325849e-01,
       -5.01257467e-01,  3.26933300e-01, -2.55044977e-01, -4.42973631e-01,
       -8.49967370e-02, -3.37745909e-01, -1.51550667e-01, -5.01257467e-01,
       -6.22336597e-02, -5.04958689e-01, -3.50978058e-01, -1.02875261e-01,
       -3.13171918e-01, -1.61947356e-01, -4.07687269e-01, -5.01650651e-01,
        1.76318123e-02, -2.55044977e-01, -6.01070643e-02,  4.31808030e+00,
       -1.29418952e-01, -4.54944945e-01,  8.99853225e-01,  3.29532472e-01,
       -5.01257467e-01, -3.13171918e-01, -4.40924538e-01, -4.74320592e-01,
       -2.56462707e-01,  1.32547357e-01, -5.04486112e-01, -3.16952532e-01,
        9.67884191e-02, -5.05983235e-01,  7.96990278e-01, -1.61947356e-01,
        5.18169991e-01, -4.54944945e-01, -5.16773107e-01, -1.28866983e-01,
        2.33126814e-01, -5.16773107e-01,  9.24506610e-01, -1.26031522e-01,
       -4.54944945e-01, -4.99210265e-01, -5.03620351e-01, -4.89679337e-01,
       -4.54944945e-01,  

In [ ]:
train_Y = train_pd['Survived'].to_numpy()
train_Y

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,

#3. Model Implementation

In [ ]:
# np.concatenate : Assemble plusieurs tableaux le long d’un axe donné.
#         axis=0 : Empiler verticalement (ajouter des lignes).
#         axis=1 : Empiler horizontalement (ajouter des colonnes).

# reshape(-1, 1) convertit (712,) → (712, 1) pour chaque variable scalaire (non déjà encodée en one-hot).


from sklearn.linear_model import LogisticRegression
import numpy as np

train_X = np.concatenate((as_categorical_pclass,as_binary_sex.reshape(-1,1),
            age_np.reshape(-1,1),sibsp_np.reshape(-1,1),
            parch_np.reshape(-1,1),fare_np.reshape(-1,1)), axis=1)
train_X

#-------------------------------Logistic Regression Model-------------------------------------#

model = LogisticRegression(random_state=0).fit(train_X, train_Y)
model.score(train_X, train_Y)


0.800561797752809

# 4.Evaluation of the Machine Learning Model

In [ ]:
test_pd = pd.read_csv("test.csv")
test_pd = test_pd[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare']]

#---------------------------Encoding & Preprocessing for the Dataset "test.csv"----------------------------#

test_pd = test_pd.fillna(test_pd['Age'].mean())

pclass = test_pd['Pclass'].to_numpy()
as_categorical_pclass = to_categorical(pclass-1, num_classes = 3)

test_pd['Sex'] = test_pd['Sex'].replace({'male' : 1, 'female': 0})
as_binary_sex = test_pd['Sex'].to_numpy()

age_np = test_pd['Age'].to_numpy()
age_np = (age_np - train_pd['Age'].mean()) / train_pd['Age'].std() #Scaling

sibsp_np = test_pd['SibSp'].to_numpy()
sibsp_np = (sibsp_np - train_pd['SibSp'].mean()) / train_pd['SibSp'].std() #Scaling

parch_np= test_pd['Parch'].to_numpy()
parch_np= (parch_np -train_pd['Parch'].mean()) / train_pd['Parch'].std() #Scaling

fare_np = test_pd['Fare'].to_numpy()
fare_np = (fare_np - train_pd['Fare'].mean()) / train_pd['Fare'].std() #Scaling


test_X = np.concatenate((as_categorical_pclass,as_binary_sex.reshape(-1,1),
            age_np.reshape(-1,1),sibsp_np.reshape(-1,1),
            parch_np.reshape(-1,1),fare_np.reshape(-1,1)), axis=1)
test_X
#-------------------------------------------------------------------------------------------------#


/tmp/ipython-input-3865200815.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_pd['Sex'] = test_pd['Sex'].replace({'male' : 1, 'female': 0})


array([[ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.5050762 ],
       [ 0.        ,  0.        ,  1.        , ...,  0.52214373,
        -0.50643136, -0.52073962],
       [ 0.        ,  1.        ,  0.        , ..., -0.55232545,
        -0.50643136, -0.4699733 ],
       ...,
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.51601717],
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.50090534],
       [ 0.        ,  0.        ,  1.        , ...,  0.52214373,
         0.66428009, -0.23062454]])

In [ ]:
predictions = model.predict(test_X)
passenger_ids = test_pd['PassengerId'].to_numpy()

sub_df = pd.DataFrame({'PassengerId' : passenger_ids, 'Survived' : predictions})
sub_df.to_csv('sub.csv', index=False)